# Generated by Django 6.0.3 on 2026-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('posteado', 'Posteado por usuario'), ('comprado', 'Comprado por la concesionaria'), ('en_venta', 'Publicado en inventario'), ('vendido', 'Vendido')], default='posteado', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_compra', models.DateTimeField(blank=True, null=True)),
                ('fecha_venta', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
