# Generated by Django 6.0.3 on 2026-03-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico'), ('glp', 'GLP')], default='gasolina', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática'), ('cvt', 'CVT')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_extra', to='inventario.vehiculo')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
