# Generated by Django 6.0.5 on 2026-05-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_vehiculo_color_vehiculo_combustible_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together={('vehiculo',)},
        ),
    ]
